// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Perpustakaan.Data;

#nullable disable

namespace Perpustakaan.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Perpustakaan.Models.Buku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JenisBukuId")
                        .HasColumnType("int");

                    b.Property<string>("Judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JumlahHalaman")
                        .HasColumnType("int");

                    b.Property<string>("Penulis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalRilis")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JenisBukuId");

                    b.ToTable("Buku");
                });

            modelBuilder.Entity("Perpustakaan.Models.HistoryBuku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aksi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BukuId")
                        .HasColumnType("int");

                    b.Property<string>("DataSebelum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataSesudah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Waktu")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HistoryBuku");
                });

            modelBuilder.Entity("Perpustakaan.Models.MasterJenisBuku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JenisBuku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterJenisBuku");
                });

            modelBuilder.Entity("Perpustakaan.Models.Buku", b =>
                {
                    b.HasOne("Perpustakaan.Models.MasterJenisBuku", "JenisBuku")
                        .WithMany()
                        .HasForeignKey("JenisBukuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JenisBuku");
                });
#pragma warning restore 612, 618
        }
    }
}
